# Generated by Django 3.0.4 on 2020-03-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='covid.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='covid.Supply'),
            preserve_default=False,
        ),
    ]
